# -----------------------------------------
# 起動時に適用するプラグイン
# -----------------------------------------

# dein自身
[[plugins]]
repo = 'Shougo/dein.vim'

# カラースキーマ
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'

# Gitコマンド
[[plugins]]
repo = 'tpope/vim-fugitive'

# git差分を左側に追加
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ファジー検索
[[plugins]]
repo = '/usr/local/opt/fzf'
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

# ""や()の補完
[[plugins]]
repo = 'Townk/vim-autoclose'

# ヌルヌルページ送り
[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
build = 'coc#util#install()'

# 不要な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# Esay motion
[[plugins]]
repo = 'easymotion/vim-easymotion'

# filer
[[plugins]]
repo = 'justinmk/vim-dirvish'

