# -----------------------------------------
# 起動時に適用するプラグイン
# -----------------------------------------

# dein自身
[[plugins]]
repo = 'Shougo/dein.vim'

# カラースキーマ
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# ステータスライン
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'
[[plugins]]
repo = 'itchyny/lightline.vim'

# 多機能セレクタ
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# ファイルツリー
[[plugins]]
repo = 'scrooloose/nerdtree'



