# -----------------------------------------
# 起動時に適用するプラグイン
# -----------------------------------------

# dein自身
[[plugins]]
repo = 'Shougo/dein.vim'

# カラースキーマ
[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

# ステータスライン
[[plugins]]
repo = 'itchyny/lightline.vim'

# Gitコマンド
[[plugins]]
repo = 'tpope/vim-fugitive'

# git差分を左側に追加
[[plugins]]
repo = 'airblade/vim-gitgutter'

# ファイルツリー
[[plugins]]
repo = 'scrooloose/nerdtree'



